#pragma checksum "C:\Users\Vagner\Documents\GitHub\Projetos Pessoais\CodeEditor-v10-integration\tools\razor-lsp-probe\fixtures\SampleMvc\Views\Home\Index.cshtml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "84fc538b63ef2de48c47355e8b7e42358cff4a5e31b3c4913ebec1ef878deedf"
// <auto-generated/>
#pragma warning disable 1591
[assembly: global::Microsoft.AspNetCore.Razor.Hosting.RazorCompiledItemAttribute(typeof(AspNetCoreGeneratedDocument.Views_Home_Index), @"mvc.1.0.view", @"/Views/Home/Index.cshtml")]
namespace AspNetCoreGeneratedDocument
{
    #line default
    using global::System;
    using global::System.Collections.Generic;
    using global::System.Linq;
    using global::System.Threading.Tasks;
    using global::Microsoft.AspNetCore.Mvc;
    using global::Microsoft.AspNetCore.Mvc.Rendering;
    using global::Microsoft.AspNetCore.Mvc.ViewFeatures;
#nullable restore
#line (1,2)-(1,17) "C:\Users\Vagner\Documents\GitHub\Projetos Pessoais\CodeEditor-v10-integration\tools\razor-lsp-probe\fixtures\SampleMvc\Views\_ViewImports.cshtml"
using SampleMvc

#nullable disable
    ;
#nullable restore
#line (2,2)-(2,24) "C:\Users\Vagner\Documents\GitHub\Projetos Pessoais\CodeEditor-v10-integration\tools\razor-lsp-probe\fixtures\SampleMvc\Views\_ViewImports.cshtml"
using SampleMvc.Models

#nullable disable
    ;
    #line default
    #line hidden
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorCompiledItemMetadataAttribute("Identifier", "/Views/Home/Index.cshtml")]
    [global::System.Runtime.CompilerServices.CreateNewOnMetadataUpdateAttribute]
    #nullable restore
    internal sealed class Views_Home_Index : global::Microsoft.AspNetCore.Mvc.Razor.RazorPage<
#nullable restore
#line (1,8)-(1,37) "C:\Users\Vagner\Documents\GitHub\Projetos Pessoais\CodeEditor-v10-integration\tools\razor-lsp-probe\fixtures\SampleMvc\Views\Home\Index.cshtml"
SampleMvc.Models.WeatherModel

#line default
#line hidden
#nullable disable
    >
    #nullable disable
    {
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_0 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("asp-controller", "Home", global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_1 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("asp-action", "Index", global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        #line hidden
        #pragma warning disable 0649
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperExecutionContext __tagHelperExecutionContext;
        #pragma warning restore 0649
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner __tagHelperRunner = new global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner();
        #pragma warning disable 0169
        private string __tagHelperStringValueBuffer;
        #pragma warning restore 0169
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperScopeManager __backed__tagHelperScopeManager = null;
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperScopeManager __tagHelperScopeManager
        {
            get
            {
                if (__backed__tagHelperScopeManager == null)
                {
                    __backed__tagHelperScopeManager = new global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperScopeManager(StartTagHelperWritingScope, EndTagHelperWritingScope);
                }
                return __backed__tagHelperScopeManager;
            }
        }
        private global::Microsoft.AspNetCore.Mvc.Razor.TagHelpers.HeadTagHelper __Microsoft_AspNetCore_Mvc_Razor_TagHelpers_HeadTagHelper;
        private global::Microsoft.AspNetCore.Mvc.Razor.TagHelpers.BodyTagHelper __Microsoft_AspNetCore_Mvc_Razor_TagHelpers_BodyTagHelper;
        private global::Microsoft.AspNetCore.Mvc.TagHelpers.AnchorTagHelper __Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper;
        #pragma warning disable 1998
        public async override global::System.Threading.Tasks.Task ExecuteAsync()
        {
#nullable restore
#line (2,3)-(4,1) "C:\Users\Vagner\Documents\GitHub\Projetos Pessoais\CodeEditor-v10-integration\tools\razor-lsp-probe\fixtures\SampleMvc\Views\Home\Index.cshtml"

    var greeting = "Olá";

#line default
#line hidden
#nullable disable

            WriteLiteral("<!DOCTYPE html>\r\n<html>\r\n");
            __tagHelperExecutionContext = __tagHelperScopeManager.Begin("head", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.StartTagAndEndTag, "84fc538b63ef2de48c47355e8b7e42358cff4a5e31b3c4913ebec1ef878deedf4756", async() => {
                WriteLiteral("\r\n    <title>");
                Write(
#nullable restore
#line (8,13)-(8,23) "C:\Users\Vagner\Documents\GitHub\Projetos Pessoais\CodeEditor-v10-integration\tools\razor-lsp-probe\fixtures\SampleMvc\Views\Home\Index.cshtml"
Model.City

#line default
#line hidden
#nullable disable
                );
                WriteLiteral("</title>\r\n");
            }
            );
            __Microsoft_AspNetCore_Mvc_Razor_TagHelpers_HeadTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.Razor.TagHelpers.HeadTagHelper>();
            __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_Razor_TagHelpers_HeadTagHelper);
            await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
            if (!__tagHelperExecutionContext.Output.IsContentModified)
            {
                await __tagHelperExecutionContext.SetOutputContentAsync();
            }
            Write(__tagHelperExecutionContext.Output);
            __tagHelperExecutionContext = __tagHelperScopeManager.End();
            WriteLiteral("\r\n");
            __tagHelperExecutionContext = __tagHelperScopeManager.Begin("body", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.StartTagAndEndTag, "84fc538b63ef2de48c47355e8b7e42358cff4a5e31b3c4913ebec1ef878deedf6095", async() => {
                WriteLiteral("\r\n    <h1>");
                Write(
#nullable restore
#line (11,10)-(11,18) "C:\Users\Vagner\Documents\GitHub\Projetos Pessoais\CodeEditor-v10-integration\tools\razor-lsp-probe\fixtures\SampleMvc\Views\Home\Index.cshtml"
greeting

#line default
#line hidden
#nullable disable
                );
                WriteLiteral(", ");
                Write(
#nullable restore
#line (11,21)-(11,31) "C:\Users\Vagner\Documents\GitHub\Projetos Pessoais\CodeEditor-v10-integration\tools\razor-lsp-probe\fixtures\SampleMvc\Views\Home\Index.cshtml"
Model.City

#line default
#line hidden
#nullable disable
                );
                WriteLiteral("</h1>\r\n    <p>Temperatura: ");
                Write(
#nullable restore
#line (12,22)-(12,40) "C:\Users\Vagner\Documents\GitHub\Projetos Pessoais\CodeEditor-v10-integration\tools\razor-lsp-probe\fixtures\SampleMvc\Views\Home\Index.cshtml"
Model.TemperatureC

#line default
#line hidden
#nullable disable
                );
                WriteLiteral(" C (");
                Write(
#nullable restore
#line (12,45)-(12,63) "C:\Users\Vagner\Documents\GitHub\Projetos Pessoais\CodeEditor-v10-integration\tools\razor-lsp-probe\fixtures\SampleMvc\Views\Home\Index.cshtml"
Model.TemperatureF

#line default
#line hidden
#nullable disable
                );
                WriteLiteral(" F)</p>\r\n    <p>Tipo: ");
                Write(
#nullable restore
#line (13,15)-(13,25) "C:\Users\Vagner\Documents\GitHub\Projetos Pessoais\CodeEditor-v10-integration\tools\razor-lsp-probe\fixtures\SampleMvc\Views\Home\Index.cshtml"
Model.Kind

#line default
#line hidden
#nullable disable
                );
                WriteLiteral("</p>\r\n\r\n");
                WriteLiteral("    <p>");
                Write(
#nullable restore
#line (16,9)-(16,34) "C:\Users\Vagner\Documents\GitHub\Projetos Pessoais\CodeEditor-v10-integration\tools\razor-lsp-probe\fixtures\SampleMvc\Views\Home\Index.cshtml"
Model.NonExistentProperty

#line default
#line hidden
#nullable disable
                );
                WriteLiteral("</p>\r\n\r\n    ");
                __tagHelperExecutionContext = __tagHelperScopeManager.Begin("a", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.StartTagAndEndTag, "84fc538b63ef2de48c47355e8b7e42358cff4a5e31b3c4913ebec1ef878deedf8510", async() => {
                    WriteLiteral("Início");
                }
                );
                __Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.TagHelpers.AnchorTagHelper>();
                __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper);
                __Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper.Controller = (string)__tagHelperAttribute_0.Value;
                __tagHelperExecutionContext.AddTagHelperAttribute(__tagHelperAttribute_0);
                __Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper.Action = (string)__tagHelperAttribute_1.Value;
                __tagHelperExecutionContext.AddTagHelperAttribute(__tagHelperAttribute_1);
                await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
                if (!__tagHelperExecutionContext.Output.IsContentModified)
                {
                    await __tagHelperExecutionContext.SetOutputContentAsync();
                }
                Write(__tagHelperExecutionContext.Output);
                __tagHelperExecutionContext = __tagHelperScopeManager.End();
                WriteLiteral("\r\n");
            }
            );
            __Microsoft_AspNetCore_Mvc_Razor_TagHelpers_BodyTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.Razor.TagHelpers.BodyTagHelper>();
            __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_Razor_TagHelpers_BodyTagHelper);
            await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
            if (!__tagHelperExecutionContext.Output.IsContentModified)
            {
                await __tagHelperExecutionContext.SetOutputContentAsync();
            }
            Write(__tagHelperExecutionContext.Output);
            __tagHelperExecutionContext = __tagHelperScopeManager.End();
            WriteLiteral("\r\n</html>\r\n");
        }
        #pragma warning restore 1998
        #nullable restore
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.ViewFeatures.IModelExpressionProvider ModelExpressionProvider { get; private set; } = default!;
        #nullable disable
        #nullable restore
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IUrlHelper Url { get; private set; } = default!;
        #nullable disable
        #nullable restore
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IViewComponentHelper Component { get; private set; } = default!;
        #nullable disable
        #nullable restore
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IJsonHelper Json { get; private set; } = default!;
        #nullable disable
        #nullable restore
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IHtmlHelper<SampleMvc.Models.WeatherModel> Html { get; private set; } = default!;
        #nullable disable
    }
}
#pragma warning restore 1591
